## Multiclass Classification Using Logistic Regressoion
In this assignment, you will perform multiclass classification using logistic regression. You will use the logistic regression library from the ``sklearn`` library. Some of the important libraries you 'may' use include the following:

**LogisticRegression from sklearn.linear_model**

**classification_report from sklearn.metrics**

**confusion_matrix from sklearn.metrics**

You can consult documentation at: 
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

## Data Set Information:

The database consists of the multi-spectral values of pixels in 3x3 neighbourhoods in a satellite image, and the classification associated with the central pixel in each neighbourhood. The aim is to predict this classification, given the multi-spectral values. In the sample database, the class of a pixel is coded as a number.

The Landsat satellite data is one of the many sources of information available for a scene. The interpretation of a scene by integrating spatial data of diverse types and resolutions including multispectral and radar data, maps indicating topography, land use etc. is expected to assume significant importance with the onset of an era characterised by integrative approaches to remote sensing (for example, NASA's Earth Observing System commencing this decade). Existing statistical methods are ill-equipped for handling such diverse data types. Note that this is not true for Landsat MSS data considered in isolation (as in this sample database). This data satisfies the important requirements of being numerical and at a single resolution, and standard maximum-likelihood classification performs very well. Consequently, for this data, it should be interesting to compare the performance of other methods against the statistical approach.

One frame of Landsat MSS imagery consists of four digital images of the same scene in different spectral bands. Two of these are in the visible region (corresponding approximately to green and red regions of the visible spectrum) and two are in the (near) infra-red. Each pixel is a 8-bit binary word, with 0 corresponding to black and 255 to white. The spatial resolution of a pixel is about 80m x 80m. Each image contains 2340 x 3380 such pixels.

The database is a (tiny) sub-area of a scene, consisting of 82 x 100 pixels. Each line of data corresponds to a 3x3 square neighbourhood of pixels completely contained within the 82x100 sub-area. Each line contains the pixel values in the four spectral bands (converted to ASCII) of each of the 9 pixels in the 3x3 neighbourhood and a number indicating the classification label of the central pixel. The number is a code for the following classes:

Number Class

1 red soil

2 cotton crop

3 grey soil

4 damp grey soil

5 soil with vegetation stubble

6 mixture class (all types present)

7 very damp grey soil

NB. There are no examples with class 6 in this dataset.

In each line of data the four spectral values for the top-left pixel are given first followed by the four spectral values for the top-middle pixel and then those for the top-right pixel, and so on with the pixels read out in sequence left-to-right and top-to-bottom. Thus, the four spectral values for the central pixel are given by attributes 17,18,19 and 20. If you like you can use only these four attributes, while ignoring the others. This avoids the problem which arises when a 3x3 neighbourhood straddles a boundary.


https://archive.ics.uci.edu/ml/datasets/Statlog+(Landsat+Satellite)


## 1. Import the data and split it into train/validate/test

Import the file '186_satimage.csv' and split it into train/validate/test set with ratio ``70/15/15``

**note: use random_state=777 whereever needed**

**note: the first 36 column are features and the last column is the class label**


In [1]:
# Importing necessary libraries
import pandas as pd  # For data manipulation and analysis
from sklearn.model_selection import train_test_split  # To split the dataset into training, validation, and testing sets
import numpy as np  # For numerical operations (though not explicitly used here)
from sklearn.metrics import confusion_matrix, classification_report  # For evaluating model performance
from sklearn.preprocessing import StandardScaler  # For standardizing the dataset
from sklearn.linear_model import LogisticRegression  # For building the logistic regression model
from sklearn.metrics import accuracy_score  # For calculating the model's accuracy

# Loading the dataset from a CSV file
data = pd.read_csv('186_satimage.csv')  # Replace with the correct path to your dataset if needed

# Separating features (X) and target labels (y)
X = data.iloc[:, :36]  # Selecting all rows and the first 36 columns as features
y = data.iloc[:, 36]  # Selecting all rows and the 37th column as the target variable

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=777)

# Further splitting the testing set into validation and testing subsets
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=0.5, random_state=777)

# Optional: Uncomment the line below to preview the first few rows of the dataset
# data.head()

## 2. Check the details of the features and labels

Check some basic statistics of the features and the label

In [2]:
# Displaying the overall shape of the dataset
print('X_data={} (rows, columns)'.format(data.shape))  # Total number of samples and features in the dataset

# Displaying the shapes of training, validation, and test feature datasets
print('X_train={}, X_val={}, X_test={} (rows, columns)'.format(X_train.shape, X_val.shape, X_test.shape))  # Number of samples in each dataset

# Displaying the shapes of training, validation, and test target labels
print('y_train={}, y_val={}, y_test={} (rows)'.format(y_train.shape, y_val.shape, y_test.shape))  # Number of target labels in each dataset
print()

# Calculating and displaying class distribution as percentages for the training set
print('Class % in y_train = {}'.format((np.unique(y_train, return_counts=True)[1] / y_train.shape[0]).round(2)))  
# Unique classes and their percentage distribution in the training set

# Calculating and displaying class distribution as percentages for the validation set
print('Class % in y_val = {}'.format((np.unique(y_val, return_counts=True)[1] / y_val.shape[0]).round(2)))  
# Unique classes and their percentage distribution in the validation set

# Calculating and displaying class distribution as percentages for the test set
print('Class % in y_test = {}'.format((np.unique(y_test, return_counts=True)[1] / y_test.shape[0]).round(2)))  
# Unique classes and their percentage distribution in the test set

# Additional statistics for more insights:
print()
print('Feature-wise mean (X_train):\n{}'.format(X_train.mean().round(2)))  # Mean of each feature in the training set
print()
print('Feature-wise standard deviation (X_train):\n{}'.format(X_train.std().round(2)))  # Standard deviation of each feature in the training set
print()
print('Target class counts in training set:\n{}'.format(np.unique(y_train, return_counts=True)))  # Count of each class in the training set


X_data=(6429, 37) (rows, columns)
X_train=(4500, 36), X_val=(964, 36), X_test=(965, 36) (rows, columns)
y_train=(4500,), y_val=(964,), y_test=(965,) (rows)

Class % in y_train = [0.24 0.11 0.22 0.1  0.11 0.23]
Class % in y_val = [0.25 0.11 0.2  0.1  0.11 0.24]
Class % in y_test = [0.23 0.12 0.18 0.1  0.11 0.25]

Feature-wise mean (X_train):
0.117596     0.01
1.241362     0.02
1.184036     0.02
0.815302     0.01
-0.158561    0.01
1.256483     0.01
1.193546     0.02
0.818486     0.01
-0.141965    0.01
0.879481     0.02
0.67001      0.01
0.40102      0.00
0.05222      0.02
1.204523     0.02
1.181239     0.02
0.758245     0.01
-0.151111    0.02
1.214967     0.02
1.187378     0.02
0.598708     0.01
-0.136658    0.01
1.01113      0.02
0.899623     0.02
0.761977     0.01
-0.085593    0.02
1.211546     0.02
1.251179     0.02
0.807707     0.01
-0.069968    0.01
1.21916      0.02
1.250463     0.02
0.597678     0.01
-0.054291    0.01
1.233342     0.02
1.262255     0.02
0.603258     0.01
dtype: fl

## 3. Train a logistic regression classifier and fine-tune the hyper parameters on the validation set

After all the fine tuning, report the best results on the validation set.

In [5]:
# Standardize the training and validation datasets
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

# Perform Logistic Regression with L2 penalty
clf = LogisticRegression(
    penalty='l2',  # L2 regularization
    C=1.0,  # Regularization strength (default value)
    max_iter=1500,  # Maximum number of iterations
    random_state=777,  # Ensure reproducibility
)

# Fit the model on the training data
clf.fit(X_train_scaled, y_train)

# Predict on the validation data
y_pred_on_val = clf.predict(X_val_scaled)

# Calculate validation accuracy
val_acc = accuracy_score(y_true=y_val, y_pred=y_pred_on_val)
print(f"L2 Regression Validation Accuracy: {val_acc:.4f}")


L2 Regression Validation Accuracy: 0.8568


# (Optional) Grid Search on hyperparameter

this is just a simple way to try all the different hyperparameters combinations to find the best one


In [11]:
# Define lists for penalties and regularization strengths (C values)
penalty_list = ['l1', 'l2', 'elasticnet', None]
C_values = [0.001, 0.01, 0.1, 1, 10, 100]

# Initialize variables to track the best hyperparameters and accuracy
best_penalty = None
best_C = None
best_acc = 0.0

# Loop over all penalty types and C values to find the best combination
for penalty_val in penalty_list:
    for C_val in C_values:
        
        # Choose solver based on the penalty type
        solver = 'saga' if penalty_val == 'elasticnet' else 'lbfgs' if penalty_val == None else 'liblinear'

        # Create a logistic regression model with the current hyperparameters
        clf = LogisticRegression(
            penalty=penalty_val,
            C=C_val,
            max_iter=1500,
            random_state=777,
            l1_ratio=0.5 if penalty_val == 'elasticnet' else None,  # Only used for elasticnet
            solver=solver
        )
        
        # Standardize features using StandardScaler
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_val_scaled = scaler.transform(X_val)
        
        # Train the model and predict on validation set
        clf.fit(X_train_scaled, y_train)
        y_pred_on_val = clf.predict(X_val_scaled)
        
        # Calculate validation accuracy
        val_acc = accuracy_score(y_true=y_val, y_pred=y_pred_on_val)
        
        print(f"Setting penalty={penalty_val}, C={C_val}, val_acc={val_acc:.4f}")
        
        # Update best parameters if current accuracy is better
        if val_acc > best_acc:
            best_acc = val_acc
            best_penalty = penalty_val
            best_C = C_val


    
    print("-"*50)

# Print the best hyperparameters and corresponding validation accuracy
print(f"Best setting penalty={best_penalty}, C={best_C}, val_acc={best_acc:.4f}")


Setting penalty=l1, C=0.001, val_acc=0.5716
Setting penalty=l1, C=0.01, val_acc=0.7593
Setting penalty=l1, C=0.1, val_acc=0.8174
Setting penalty=l1, C=1, val_acc=0.8371
Setting penalty=l1, C=10, val_acc=0.8434
Setting penalty=l1, C=100, val_acc=0.8413
--------------------------------------------------
Setting penalty=l2, C=0.001, val_acc=0.7459
Setting penalty=l2, C=0.01, val_acc=0.7832
Setting penalty=l2, C=0.1, val_acc=0.8216
Setting penalty=l2, C=1, val_acc=0.8351
Setting penalty=l2, C=10, val_acc=0.8423
Setting penalty=l2, C=100, val_acc=0.8413
--------------------------------------------------
Setting penalty=elasticnet, C=0.001, val_acc=0.6784
Setting penalty=elasticnet, C=0.01, val_acc=0.8164
Setting penalty=elasticnet, C=0.1, val_acc=0.8371
Setting penalty=elasticnet, C=1, val_acc=0.8568
Setting penalty=elasticnet, C=10, val_acc=0.8537
Setting penalty=elasticnet, C=100, val_acc=0.8496
--------------------------------------------------
Setting penalty=None, C=0.001, val_acc=0.85

/home/zerk/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/zerk/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(


Setting penalty=None, C=0.01, val_acc=0.8517
Setting penalty=None, C=0.1, val_acc=0.8517


/home/zerk/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(


Setting penalty=None, C=1, val_acc=0.8517
Setting penalty=None, C=10, val_acc=0.8517


/home/zerk/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/home/zerk/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(


Setting penalty=None, C=100, val_acc=0.8517
--------------------------------------------------
Best setting penalty=elasticnet, C=1, val_acc=0.8568


## 4. Do the final test on the test set

Do the final scoring on the test set. Report different measure and show the confusion matrix. Record your observations.

In [12]:
clf = LogisticRegression(
        penalty='elasticnet',
        C=1,
        max_iter=1000,
        random_state=777,
        l1_ratio=0.5,
        solver='saga'
    )

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

clf.fit(X_train_scaled, y_train)

y_pred_on_test = clf.predict(X_test_scaled)
test_acc = accuracy_score(y_true=y_test, y_pred=y_pred_on_test)

print(f"Accuracy on test set= {test_acc:.4f}")

matrix = confusion_matrix(y_test,y_pred_on_test)
print("-"*50)
print(matrix)

class_report = classification_report(y_test,y_pred_on_test)
print("-"*50)
print(class_report)



Accuracy on test set= 0.8632
--------------------------------------------------
[[216   0   4   0   1   0]
 [  1 111   0   0   4   0]
 [  0   0 167   9   0   0]
 [  3   0  22  32   6  38]
 [  2   4   0   0  89  10]
 [  0   0   0  16  12 218]]
--------------------------------------------------
              precision    recall  f1-score   support

           1       0.97      0.98      0.98       221
           2       0.97      0.96      0.96       116
           3       0.87      0.95      0.91       176
           4       0.56      0.32      0.41       101
           5       0.79      0.85      0.82       105
           7       0.82      0.89      0.85       246

    accuracy                           0.86       965
   macro avg       0.83      0.82      0.82       965
weighted avg       0.85      0.86      0.85       965

